### ISSUE TITLE
[Question] Live reloading

### ISSUE THREAD

**Issue by lpan** [bholtbholt/step-sequencer#1]
Hi Brian,

I have to say that this is a really cool project! I am currently learning Elm and I notice that live reloading is not enabled when I run `yarn start`. Is it possible to configure `elm-reactor` so that it supports live reloading? Or, I have to use something like [elm-live](https://github.com/tomekwi/elm-live). Thanks a lot!

Lawrence

**Comment by bholtbholt** [comment]
Thanks @lpan 😄 

I've used web pack hot reloading in the past, but I was aiming to make this repo simpler as an example of what defaults are like in Elm, which is why I used `elm-reactor`. As far as I know, the reactor isn't very configurable and doesn't currently support live-reloading.

I haven't used `elm-live` yet, but that looks like it'd do the trick!
